// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/KentaKudo/go-todo-graphql/internal/pb/service"
)

type NewTodo struct {
	Title       *string              `json:"title"`
	Description *string              `json:"description"`
	Status      *service.Todo_Status `json:"status"`
}
